In [1]:
import numpy as np

a=np.array([1,2,3])
a


array([1, 2, 3])

In [2]:
## 2D and 3D array 
b=np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c=np.array([[[1,2],[4,5]],[[6,7],[7,8]]])
c  ## number of elements must be same for all rows and columns 


array([[[1, 2],
        [4, 5]],

       [[6, 7],
        [7, 8]]])

In [8]:
## dtype 
c.dtype


dtype('int32')

In [9]:
## shape 
c.shape


(2, 2, 2)

In [13]:
## dtpe given by user 
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [15]:
## np.a-range() 

# arr=np.arange(start,end,step)

## all the odd number from 1 to 100 

odd_num=np.arange(1,100,2)
odd_num


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [16]:
## even number from 1 to 100
even_num=np.arange(2,101,2)
even_num


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [17]:
## reshape the array 
np.arange(12)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(12).reshape(3,2,2)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
## np.ones and np.zeros
np.ones((3,4))

## in ones and zeros 
## by default dtype is float 


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
### np.random
np.random.random((3,4))  ## module.class_name.method


array([[0.71337014, 0.75917558, 0.41107878, 0.33517024],
       [0.28056419, 0.54395379, 0.01083975, 0.12695112],
       [0.3536703 , 0.27492064, 0.87232185, 0.23126782]])

In [ ]:
## np.linspace
np.linspace(-10,10,10,dtype=int)

## np.linspace(start,stop,num want to generate)
## interval is automatically taken



array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [30]:
## Identity Matrix
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Attributes


In [ ]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8,dtype=int).reshape(2,2,2)



In [32]:
## shape 
a3.shape


(2, 2, 2)

In [33]:
## size 
a3.size


8

In [34]:
## dtpe 
a1.dtype


dtype('int32')

In [35]:
## itemsize
a3.itemsize


4

In [37]:
## dtpe
a1.dtype


dtype('int32')

In [40]:
## Changing Data Type 
## astype 

a3.astype(np.int32)
a3.dtype


dtype('int32')

## Array Operations 


In [42]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
## Scalar Operations 

## arithmetic operations 

a1**3


array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [45]:
## relational 
a2==15


array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [47]:
## Exponent 
a1 ** 2


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
## vector operation 
## arithmetic

a1=np.arange(12).reshape(3,4)
a2=np.arange(12).reshape(3,4)

# all the size and elements msu be same for mutliplication 



In [53]:
a1*a2


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

Array Functions 


In [62]:
##  by default random.random give number from 0 to 1 if not any range is provided 
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1


array([[62., 66., 23.],
       [20., 96., 79.],
       [57.,  9., 34.]])

In [63]:
## max/min/sum/product 

## 0 -> col and 1 -> row 

np.prod(a1,axis=0)



array([70680., 57024., 61778.])

In [64]:
## max 
np.max(a1)


96.0

In [65]:
## min 
np.min(a1)


9.0

In [68]:
## sum
sum_num=np.arange(12).reshape(3,4)
print(sum_num)
np.sum(sum_num)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


66

In [78]:
## Write a program to find the sum of all even number from 1 to 100 
num=np.arange(2,101,2)
print(num)
np.sum(num)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


2550

In [74]:
## Write a program to find the sum of all odd number from 1 to 100 
nums_1=np.arange(1,100,2)
print(nums_1)
np.sum(nums_1)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


2500

In [79]:
## mean/median/std/var

## var 
np.var(num)


833.0

In [80]:
## mean
np.mean(num)


51.0

In [81]:
## median
np.median(num)


51.0

In [ ]:
## Trignomatery Function 

np.sin(a1)


array([[-0.7391807 , -0.02655115, -0.8462204 ],
       [ 0.91294525,  0.98358775, -0.44411267],
       [ 0.43616476,  0.41211849,  0.52908269]])

In [84]:
## dot product 
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [85]:
## log and exponents
np.exp(a1)


array([[8.43835667e+26, 4.60718663e+28, 9.74480345e+09],
       [4.85165195e+08, 4.92345829e+41, 2.03828107e+34],
       [5.68572000e+24, 8.10308393e+03, 5.83461743e+14]])

In [97]:
np.log(a1)


array([[4.12713439, 4.18965474, 3.13549422],
       [2.99573227, 4.56434819, 4.36944785],
       [4.04305127, 2.19722458, 3.52636052]])

In [98]:
## round /floor/ceil
n=np.array(np.random.random((2,3))*100)
print(n)
np.ceil(n)


[[38.74007208 88.80611509 46.68267406]
 [89.11058672 84.70351309 79.11684708]]


array([[39., 89., 47.],
       [90., 85., 80.]])

In [99]:
np.floor(n)


array([[38., 88., 46.],
       [89., 84., 79.]])

In [101]:
np.round(n)


array([[39., 89., 47.],
       [89., 85., 79.]])

## Indxing and Slicing 


In [102]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])